<?php

/**
 * IDE stub to make LSP happy that those constants are defined.
 */

if (false) {
define('FILECARTON_ROOT_PATH', '');
define('FILECARTON_READONLY', false);
define('FILECARTON_REPO_NAME', 'Files');
define('FILECARTON_BRANDING', '');

define('FILECARTON_PATHINFO_OFFSET', 0);
define('FILECARTON_ASSET_URL', '');

define('FILECARTON_MAX_EDIT_SIZE', 5 * 1024 * 1024);

define('FILECARTON_ARCHIVE_MAX_FILES', 10000);
define('FILECARTON_ARCHIVE_MAX_SIZE', 2 * 1024 * 1024 * 1024);

define('FILECARTON_UPLOAD_MAX_FILE_SIZE', 10 * 1024 * 1024 * 1024);
define('FILECARTON_UPLOAD_CHUNK_SIZE', 5 * 1024 * 1024);
define('FILECARTON_UPLOAD_MAX_CHUNKS', 10000);
define('FILECARTON_UPLOAD_MAX_DEPTH', 50);
define('FILECARTON_CHUNK_EXPIRY', 86400);
define('FILECARTON_CHUNK_CLEANUP_CHANCE', 10);

define('FILECARTON_SEARCH_DEFAULT_LIMIT', 200);
define('FILECARTON_SEARCH_MAX_LIMIT', 1000);
define('FILECARTON_SEARCH_MAX_SCAN', 100000);

define('FILECARTON_SENDFILE', false);

define('FILECARTON_DEV_SERVER', false);
}
